spring:
  application:
    name: email
  kafka:
    consumer:
      bootstrap-servers: 192.168.99.105:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: moisesvidal09@gmail.com
    password: mflkgolomfzinqdv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true